<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MDExport</RootNamespace>
    <AssemblyName>MDExport</AssemblyName>
    <Version>1.2.3</Version>
    <FileVersion>1.2.3.0</FileVersion>
    <AssemblyVersion>1.2.3.0</AssemblyVersion>
    <Product>MDExport</Product>
    <Company>MDExport</Company>
    <Copyright>Copyright (c) 2026</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2535.41" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\PreviewTemplate.html" />
    <Resource Include="Assets\MarkdownReference.md" />
    <Resource Include="Assets\icon.png" />
    <Resource Include="Assets\icon.ico" />
  </ItemGroup>

</Project>
